server:
  port: 8081

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
    listener:
      type: BATCH
      AckMode: MANUAL_IMMEDIATE
    streams:
      application-id: streams-filter-application
      bootstrap-servers: localhost:9092
